// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCBarDBv1;

[Table("DrinkFlat")]
public partial class DrinkFlat
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(50)]
    public string AlcoholicPart { get; set; }

    public int AlcoholicPartAmount { get; set; }

    [Required]
    [StringLength(50)]
    public string NonAlcoholicPart { get; set; }

    public int NonAlcoholicPartAmount { get; set; }
}